### ISSUE TITLE
Rendu des forêts / prairies (OpenMapTiles)

### ISSUE THREAD

**Issue by sylvain-m** [QwantResearch/qwantmaps#10]
_(j'espère qu'il est possible de déposer une issue en Français : s'il est obligatoire de traduire en anglais, je ferai l'effort d'essayer)_

Bravo pour QwantMaps que je découvre et qui me semble vraiment très prometteur pour se désintoxiquer des outils G**gle M*ps !

Je vous signale un problème de rendu que je trouve gênant dans les territoires ruraux.
J'ai bien conscience que le rendu s'effectue via OpenMapTiles, mais peut-être avez-vous la main sur le choix du style ou sur la création d'un style spécifique pour Qwant Maps.

Comme le montre la capture d'écran ci-dessous, le rendu des prairies est d'un vert beaucoup plus soutenu que celui des Forêts.
Hors, dans la majorité des cartes, une forêt est beaucoup plus structurante et dois donc être plus visible que les prairies (d'autant plus que l'occupation du sol est très fluctuante d'une année à l'autre).

![screenshot_2018-11-28 qwant local - le moteur de recherche qui respecte votre vie privee](https://user-images.githubusercontent.com/11629210/49165461-909dae00-f331-11e8-9492-cdd521a48914.png)

Sur la capture d'écran ci-dessus, se trouve un très grand massif forestier (forêt d'Ecouves), qui n'est presque pas visible alors que les prairies environnantes apparaissent de manière anormalement importante.

Si jamais ce problème était à signaler aux développeurs de OpenMapTiles, merci de me le dire et de me préciser les caractéristiques (identifiants) du rendu utilisé pour Qwant Maps.

**Comment by nlehuby** [comment]
Hello,

Merci pour tes retours et tes encouragements :heart:

Ta remarque est très judicieuse, c'est très bien vu : il faut surement qu'on rende un peu plus visible le vert des forêts et/ou un peu moins pimpant celui des prairies.

Nous accepterons avec plaisir une contribution sur ce sujet :wink:
Cela concerne le style de la carte, qui est dans ce repo : https://github.com/QwantResearch/qwant-basic-gl-style. Il faudrait revoir les couleurs appliquées sur la couche `landcover`.

Notre doc ~~est à chier~~ reste à écrire, donc si toi ou quelqu'un d'autre veut bosser sur ce sujet, je vous invite à poster un petit message ici, on se tiendra dispo pour aider à la prise en main et l'installation d'un environnement de développement qui permette de tester la modif.

**Comment by sylvain-m** [comment]
Ok, je vais tenter de le faire dans le bon repo.
N'étant pas vraiment développeur, je vais ouvrir une issue là bas pour cela, mais en essayant quand même de proposer les modifications correspondantes.

A suivre ! :)

**Comment by nlehuby** [comment]
Corrigé dans https://github.com/QwantResearch/qwant-basic-gl-style/pull/62

**Comment by sylvain-m** [comment]
Super :+1: 
Pour mon information, et sans aucune impatience de ma part, quels sont les délais envisageables pour que la modification soit opérationnelle sur Qwant Maps ?

**Comment by nlehuby** [comment]
Une à deux semaines en moyenne pour ce genre de modifications. Tu l'auras pour Noël :gift_heart:
