### ISSUE TITLE
Bug on opening_hours

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#100]
I found a bug on this node : 

- OSM : https://www.openstreetmap.org/node/2309466395
- QwantMaps : https://www.qwant.com/maps/place/osm:node:2309466395@Pizza_Story/#map=18/45.7709834/4.8619305

Thanks !

**Comment by jonsger** [comment]
The parser for the opening hours is [idunn](https://github.com/QwantResearch/idunn). So maybe you should open a bug in that repo...

**Comment by remi-dupre** [comment]
Hi!

 The issue [has recently been fixed](https://github.com/QwantResearch/idunn/pull/154). We just tested the correction in our development environment and it should soon be available in production!

![Screenshot_2020-07-27_14-45-25](https://user-images.githubusercontent.com/1173464/88543303-0e8aee80-d018-11ea-96ba-b54b07203dc0.png)

Thanks for your feedback!

**Comment by amatissart** [comment]
The fix has been deployed to production, and is now visible on https://www.qwant.com/maps
