### ISSUE TITLE
Unable to search by house number

### ISSUE THREAD

**Issue by onny** [QwantResearch/qwantmaps#110]
Hi,
trying to find an address by house number in Germany fails. Instead Qwant Maps is showing me the street only. My search term is: ``Erzbergerstraße 60, Karlsruhe`` which equals to ``Streetname Housenumber, City``:

![2020-04-04-202327_grim](https://user-images.githubusercontent.com/757752/78458511-40b3c180-76b2-11ea-9e25-ba42aed06105.png)

Guess this feature should be quite essential and maybe it is working in other countries already.

Best regards
Jonas

**Comment by amatissart** [comment]
Hi Jonas,

Search for exact addresses (with house numbers) is indeed currently limited to France. 
The good news is we are currently working on extending this coverage with datasets from OpenStreetMap or [OpenAddresses](https://openaddresses.io/).  
In the next step most of European countries should be covered, including Germany.

Thanks for your patience, and stay tuned for updates.

**Comment by amatissart** [comment]
Our address coverage has been extended in Europe. You should be able to search for addresses with house number in Germany now.

I am closing this issue. Let us know if you encounter any problem.
