### ISSUE TITLE
Add amenity=coworking_space

### ISSUE THREAD

**Issue by axelos** [QwantResearch/qwantmaps#12]
Hello,

Tristan NINOT a annoncé ce service lors d'un événement sur le libre le mois dernier, il n'aura pas fallu entendre bien longtemps pour la concrétisation.

Bref, j'en profite pour proposer un premier ajout, une simple prise en compte du tag amenity=coworking_space pour représenter un lieu qui servira entre autre à organiser des complétions de données issus de cartoparties :) , et donc améliorer la précision de Qwant Map !

Cordialement, Axel.

**Comment by Hywan** [comment]
Tristan NINOT est un cousin de Tristan NiTot :-p?

**Comment by nlehuby** [comment]
:+1:

Si quelqu'un veut nous aider sur ce sujet :

- le tag est à ajouter dans le [fichier de configuration](https://github.com/openmaptiles/openmaptiles/blob/master/layers/poi/mapping.yaml) du génial [OpenMapTiles](https://github.com/openmaptiles/openmaptiles)
- le picto est à proposer au projet [maki](https://github.com/mapbox/maki)

L'occasion de contribuer à deux projets opensource :heart: de l'écosystème OSM ;)

**Comment by axelos** [comment]
En plus d’être le premier à écrire une proposition, je suis aussi le premier à écrire une bêtise !
C'est leisure=hackerspace (et non pas amenity=coworking_space) que je voulais proposer.

amenity=coworking_space correspond a un lieu ou des individus se retrouve dans un même espace pour travailler généralement individuellement,
leisure=hackerspace est plutôt un lieu ou des individus se retrouve pour collaborer sur le même projet, ce qui correspond aux Fab Lab.

**Comment by nlehuby** [comment]
Pour info, les `leisure=hackerspace` sont déjà affichés. Voir par exemple https://www.qwant.com/maps/place/osm:node:2798968100@La_Paillasse/#map=18/48.8683141/2.3525857

**Comment by axelos** [comment]
Merci pour l'info. Que faire alors ? Implémenter tout de même amenity=coworking_space (ça ne coûte rien) ? Il faudra en revanche utiliser un autre picto.

**Comment by amatissart** [comment]
tracked in #83
