### ISSUE TITLE
Rendering of private garden

### ISSUE THREAD

**Issue by lgiard** [QwantResearch/qwantmaps#13]
Bonjour,

J'ai remarqué que les jardins privés (en général des jardins résidentiels) apparaissent très fortement sur la carte avec un icône indiquant un jardin pour chacun d'entre eux, j'imagine que l'idée de base est de montrer où se situe les jardins publics.

Je proposerais donc de ne pas mettre cette icône pour les éléments avec les tags "leisure=garden" + "access=private" (ce sont les tags utilisés pour les jardins privés en général). 

Un exemple est le centre ville de Leuven (Belgique), et il y a d'autres villes comme ça en Belgique : https://www.qwant.com/maps/#map=16.79/50.8798593/4.7096927

Bien à vous,

**Comment by nlehuby** [comment]
Hello,

Merci pour ce retour !

C'est bien l'idée, mais ce n'est pas que les jardins publics, voir par exemple aussi celui-ci qu'on veut pouvoir afficher : https://www.openstreetmap.org/way/558329722

On va regarder ce qu'on peut faire là-dessus.

**Comment by hugobqd** [comment]
Je suis d'accord avec @lgiard, les leisure=garden + access=private ne méritent pas d'icônes. Autre exemple ici https://www.qwant.com/maps/#map=17.56/47.3841626/0.6702850

**Comment by amatissart** [comment]
Un fix a été implémenté dans https://github.com/QwantResearch/openmaptiles/pull/19  
Il faudra attendre la prochaine régénération complètes des tuiles pour qu'il soit effectif

**Comment by amatissart** [comment]
Depuis, le correctif a été appliqué en production. Les jardins sans nom ne portent maintenant plus d'icones.
