### ISSUE TITLE
Allow CTRL-C inputs

### ISSUE THREAD

**Issue by Prometheos2** [QwantResearch/qwantmaps#130]
Hello,

I noticed it was impossible to copy text (e.g., a place's address) by using _CTRL+C_.
Every time, the app considers the _C_ input to be an input intended for the search bar instead, and switches focus, accidentally canceling the copy.

Might there be any workaround or solution easy to implement?

**Comment by bbecquet** [comment]
Hi,
This is actually a usability bug, we are taking it into account. It should be fixed on the web site in the next days.
Thanks a lot for your feedback.

**Comment by Prometheos2** [comment]
Hello,
Thank you for taking care of the bug so quickly.

Is there an estimated time for the push on production? 
It would be awkward to say the fix didn't work if it's not on live server yet ^^'

Have a nice day!

**Comment by bbecquet** [comment]
Hello,
We finally deployed a new version, including the fix of this issue among other fixes and a redesign of the directions feature.
Thank you again for your contribution :)

**Comment by Prometheos2** [comment]
Hello,
You're welcome.
Thank you again for your work!
Have a nice day.
