### ISSUE TITLE
No map on the screen

### ISSUE THREAD

**Issue by Elowarp** [QwantResearch/qwantmaps#132]
Hi, so I wanted to try the beta of the Qwant Maps and nothing looked to work but I was wrong, it was just the map, the route works etc. 
Soo I checked out the console and it says this :
`Content Security Policy: L’analyse de « script-src-elem » a échoué, car la directive est inconnue.`

`Error: Failed to initialize WebGL
    _setupPainter https://www.qwant.com/maps/statics/build/javascript/vendors~map.bundle.js:1
    a https://www.qwant.com/maps/statics/build/javascript/vendors~map.bundle.js:1
    t https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
    u https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    _invoke https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    t https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    Ce https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
    a https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
vendors~map.bundle.js:1:21480`

`WebGL warning: <Create>: Refused to create native OpenGL context because of blacklist entry: FEATURE_FAILURE_OLD_FGLRX vendors~map.bundle.js:1:718412`

`Failed to create WebGL context: WebGL creation failed: 
Refused to create native OpenGL context because of blacklist entry: FEATURE_FAILURE_OLD_FGLRX
Exhausted GL driver options. vendors~map.bundle.js:1:718412`

`WebGL warning: <Create>: Refused to create native OpenGL context because of blacklist entry: FEATURE_FAILURE_OLD_FGLRX vendors~map.bundle.js:1:718448`

`Failed to create WebGL context: WebGL creation failed:  Refused to create native OpenGL context because of blacklist entry: FEATURE_FAILURE_OLD_FGLRX
 Exhausted GL driver options. vendors~map.bundle.js:1:718448`

`Uncaught (in promise) Error: Failed to initialize WebGL.
    a https://www.qwant.com/maps/statics/build/javascript/vendors~map.bundle.js:1
    t https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
    u https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    _invoke https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    t https://www.qwant.com/maps/statics/build/javascript/bundle.js:11
    Ce https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
    a https://www.qwant.com/maps/statics/build/javascript/map.bundle.js:1
vendors~map.bundle.js:1:702752`

I have every thing like the search bar, the route etc(I tried to go from Toulouse to Paris). I'm on debian 9.13, firefox 78.6.1esr (64 bits).
![Capture d’écran_2021-01-14_22-36-38](https://user-images.githubusercontent.com/32903478/104652625-add09a80-56b9-11eb-94cc-68c208ce7624.png)
(This is the link by the way : [Here](https://www.qwant.com/maps/routes/?mode=driving&origin=admin%3Aosm%3Arelation%3A35738%40Toulouse&selected=0&details=true&destination=admin%3Aosm%3Arelation%3A7444%40Paris_75000-75116) )

**Comment by amatissart** [comment]
Duplicated by #133
