### ISSUE TITLE
Incomplete rendering of opening_hours

### ISSUE THREAD

**Issue by francois2metz** [QwantResearch/qwantmaps#15]
Some opening hours are not correctly displayed.

For instance: `Mo-Fr 11:30-15:00, We-Mo 18:00-23:00` is rendered as 

Monday 	06:00 PM - 11:00 PM
Tuesday 	11:30 AM - 03:00 PM 
Wednesday 06:00 PM - 11:00 PM
Thursday 06:00 PM - 11:00 PM
Friday 06:00 PM - 11:00 PM
Saturday 06:00 PM - 11:00 PM
Sunday 06:00 PM - 11:00 PM

Except for tuesday, the hours `11:30-15:00` are missing.

See the example there: https://www.qwant.com/maps/place/osm:node:2327181277@Tha%C3%AF_in_box#map=18.09/48.8140318/2.3217878

**Comment by nlehuby** [comment]
Thanks for this valuable bug report.
We use the wonderful Humanized Opening Hours python module to handle this in Qwant Maps, here is the according issue: https://github.com/rezemika/humanized_opening_hours/issues/28

Feel free to add more use cases in this repo, they are looking for feedback ;)
