### ISSUE TITLE
No picto for shop=butcher

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#17]
A moins que ce soit le picto choisi, il ne me semble pas que le picto des boucheries soit ok.

On peut en voir un wagon ici : https://www.qwant.com/maps/#map=18.67/48.8159859/2.3205266

Mais le projet QwantMaps est top, enfin une vraie interface à OSM et 100% FrenchTech :)

**Comment by nlehuby** [comment]
Merci du feedback :+1: 

Une suggestion de meilleur picto à utiliser parmi ceux proposés par [maki](https://github.com/mapbox/maki) ?

**Comment by bristow** [comment]
S'il faut choisir parmi Maki, alors, nous n'avons pas le choix, ce sera parmi ces 2 : 

- https://github.com/mapbox/maki/blob/master/icons/slaughterhouse-11.svg
- https://github.com/mapbox/maki/blob/master/icons/slaughterhouse-15.svg

Le ![slaughterhouse-11.svg](https://github.com/mapbox/maki/blob/master/icons/slaughterhouse-11.svg
) ou le ![slaughterhouse-15.svg](https://github.com/mapbox/maki/blob/master/icons/slaughterhouse-15.svg)

**Comment by nlehuby** [comment]
le `slaughterhouse-11` me semble ok :+1:
Si quelqu'un veut contribuer, la modif est à faire dans ce [fichier de configuration](https://github.com/QwantResearch/qwant-basic-gl-style/blob/master/icons.yml) qui permet d'associer chaque catégorie de lieu d'intérêt à un picto.

Et sinon, si quelqu'un veut faire un picto plus adapté, il faut se pencher sur [les bonnes pratiques de design de maki](https://www.mapbox.com/maki-icons/guidelines/) et leur faire une proposition.

**Comment by nlehuby** [comment]
c'est fait !

![shop_butcher](https://user-images.githubusercontent.com/919962/51320004-d4be4c80-1a5e-11e9-8e59-afbbe094c003.png)
