### ISSUE TITLE
String 'See More' not translated in french

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#18]
Quand on utilise un smartphone (ou petit écran) et que l'on clique sur un POI, on voit un bouton apparaître 'See more' qui n'est pas traduit en français. 

Je fais comme les autres, je continue à ouvrir des issues en français du coup :p

Merci :)

**Comment by bristow** [comment]
Du coup, c'est un bouton 'hardcoded' si 100% des chaines sont traduites ?

**Comment by nlehuby** [comment]
Non :rofl:  c'est qu'il faut qu'on ré-importe les chaines traduites dans le projet.
Cela sera corrigé à la prochaine mise à jour. 
Encore merci du feedback :wink:

**Comment by bristow** [comment]
J'ai fait une demande pour rejoindre l'équipe sur Transifex, je ne sais pas si vous acceptez facilement :)
En fait, j'ai repéré un problème de typo sur 'cimetiére' que je voulais corriger.

**Comment by nlehuby** [comment]
demande approuvée ;)

**Comment by bristow** [comment]
:+1: 
Du coup, j'ai fait 3 demandes de suggestions, je ne pense pas avoir la main pour corriger directement (et en plus, je ne maitrise pas trop Transifex) : 

- chalet -> meublé de tourisme
- cimetiére -> cimetière
- hostel -> auberge de jeunesse
