### ISSUE TITLE
dont focus searchbar permanently

### ISSUE THREAD

**Issue by dex2000** [QwantResearch/qwantmaps#20]
Steps to reproduce

1. click in the map
2. type: "+"
Map is zooming (good)
3. type "+" again
"+" is in the searchbox, no zoom (bad)

**Comment by nlehuby** [comment]
Thanks for your feedback!

It would indeed improve accessibility.

If you or anyone else want to propose us a patch about this, the Qwant Maps component that need to be updated is [erdapfel](https://github.com/QwantResearch/erdapfel), and [this javascript function](https://github.com/QwantResearch/erdapfel/blob/master/views/index.ejs#L52) may be a good starting point ;)

**Comment by nlehuby** [comment]
you can now use the keyboard to zoom and pan the map  :arrow_right: :arrow_right:
