### ISSUE TITLE
Menu for embed a map on a website

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#22]
As on OpenStreetMap.org, it would be interesting to have the possibility to share a map to integrate it into a website.

Don't forget to use OEmbed : https://oembed.com/

It's very useful for teachers :)

**Comment by nlehuby** [comment]
Thanks for your feedback.

We are not sure yet this is a feature we want: we cannot certified anything about the privacy of our user if he/she uses Qwant Maps embedded into another website :disappointed: 

For now, I suggest you to use the share links that point towards a location or a point of interest instead.

**Comment by Nuc1eoN** [comment]
I second this request. I think it would be much better for the users Privacy if the site uses Quant Maps as an embeded map (eg good for contact pages) rather than google maps.
