### ISSUE TITLE
No ShoeMaker on QwantMaps

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#23]
This node https://www.openstreetmap.org/node/5644129277 is not in Qwant Maps :(

Thanks

**Comment by nlehuby** [comment]
Thanks for this suggestion :+1:

This is a change to perform in [OpenMapTiles project](https://github.com/openmaptiles/openmaptiles), to add it to the poi layer.

Any idea for the picto to use (from the [maki project](https://github.com/mapbox/maki)) ?

**Comment by bristow** [comment]
For the picto : https://github.com/mapbox/maki/blob/master/icons/shoe-11.svg
or https://github.com/mapbox/maki/blob/master/icons/shoe-15.svg

**Comment by amatissart** [comment]
tracked in #83
