### ISSUE TITLE
Daily OSM updates are not enabled yet

### ISSUE THREAD

**Issue by PierreGaujal** [QwantResearch/qwantmaps#27]

**Comment by hugobqd** [comment]
Il serai en effet très intéressant pour le visiteur et pour le contributeur OSM — qui est remotivé comme jamais par l'arrivé de Qwant maps — d'avoir des infos concernant la mise à jours des données :  

- De quand dates les informations présentées ?
- À quelle fréquence seront-elles mises-à-jour.
- Peux-t'on activer un refresh ?

**Comment by amatissart** [comment]
On partage complètement ce besoin. À nous aussi ça nous parait important et motivant que les contributions à OSM soient visibles sur Qwant Maps ! 

On vise en effet à intégrer les évolutions des données OSM quotidiennement. Mais comme vous avez pu remarquer, ce n'est pas encore le cas en production sur https://www.qwant.com/maps. On est encore en phase de tests sur ce point.  
Notamment pour coordonner les màj des tuiles avec les données utilisées par l'autocomplétion.
C'est en bonne voie. Encore un peu de patience... :hourglass_flowing_sand:

En attendant, les données sont mises à jour ponctuellement lors d'un réimport complet. À quelques semaines d'intervalle environ. Actuellement, les données correspondent à l'état de la base OSM au 31 décembre 2018.

**Comment by PierreGaujal** [comment]
> On partage complètement ce besoin. À nous aussi ça nous parait important et motivant que les contributions à OSM soient visibles sur Qwant Maps !
> 
> On vise en effet à intégrer les évolutions des données OSM quotidiennement. Mais comme vous avez pu remarquer, ce n'est pas encore le cas en production sur https://www.qwant.com/maps. On est encore en phase de tests sur ce point.
> Notamment pour coordonner les màj des tuiles avec les données utilisées par l'autocomplétion.
> C'est en bonne voie. Encore un peu de patience... 
> 
> En attendant, les données sont mises à jour ponctuellement lors d'un réimport complet. À quelques semaines d'intervalle environ. Actuellement, les données correspondent à l'état de la base OSM au 31 décembre 2018.

Merci pour cette réponse ! La question est liée à un réel intérêt pour Qwant Maps et tout ce que Qwant de manière générale peut représenter, et les contributions OSM participent directement au projet.

**Comment by hugobqd** [comment]
Bonjour, est-ce qu'une mise à jour des donnée OSM dans QM est prévue prochainement ?

**Comment by nlehuby** [comment]
Bonjour,
oui, on va mettre à jour les données dans les prochains jours. Encore un peu de patience :hourglass_flowing_sand:

**Comment by hugobqd** [comment]
Je remarque que les données ne sont pas mises à jour simultanément. 
Exemple: ce node dont l'icône indique le nom "récemment" changé sur OSM (21 jours) alors que le cartouche indique encore les anciennes infos. Cela relance ma curiosité sur la mise à jours des données. Pouvons nous rêver d'un changelog ?

<img width="509" alt="Capture d’écran 2019-03-14 à 20 37 46" src="https://user-images.githubusercontent.com/35178/54386558-89f53580-4699-11e9-8dd8-a1456b978b12.png">
https://www.qwant.com/maps/place/osm:node:3577423307

**Comment by nlehuby** [comment]
Ah, je vois qu'il y en a qui ont l'oeil :eyes: 
On peut en effet constater temporairement des différences entre les informations affichées sur la carte, le cartouche d'info et le moteur de recherche pendant qu'une mise à jour de données est en cours. Cela ne dure normalement que quelques heures. Les choses sont d'ailleurs rentrées dans l'ordre pour ce node en question :wink:

**Comment by nlehuby** [comment]
ça y est : Qwant Maps se met à jour automatiquement et régulièrement avec OpenStreetMap :tada: 
La doc contient également un peu plus de détails sur le process de mise à jour : https://github.com/QwantResearch/qwantmaps#osm-updates-
