### ISSUE TITLE
D'où proviennent les adresses

### ISSUE THREAD

**Issue by lenny31** [QwantResearch/qwantmaps#28]
L'affichage indique une adresse erronée, d'où vient-elle ?

 ![qwantmapshommodernerreur](https://user-images.githubusercontent.com/7862384/52005653-841d0980-24ca-11e9-9ddf-ec7fe02e097c.JPG)

l'adresse pages jaunes est correcte 

![qwanthommodernepagesjaunes](https://user-images.githubusercontent.com/7862384/52005680-8ed79e80-24ca-11e9-830d-d8fe430175ef.JPG)

Dans osm un nœud proche les tags addr:* (https://www.openstreetmap.org/node/790857493)
Un le POI porte les tags contact:* pour ne pas créer de noeuds adresse en doublon (https://www.openstreetmap.org/node/790866588)

Cordialement

**Comment by nlehuby** [comment]
Bonjour,

S'ils sont renseignés, nous utilisons les tags OSM `addr:*` pour déterminer l'adresse. Sinon, nous tentons de déterminer au mieux une adresse approchante par [géocodage inversé](https://fr.wikipedia.org/wiki/G%C3%A9ocodage_invers%C3%A9). Sur des lieux situés à des croisements de rue, ce n'est pas forcément évident ...

Je ne connais pas cette pratique d'utilise `contact:*` pour ne pas dupliquer d'adresses et ces tags ne sont pas documentés. Est-ce vraiment une bonne pratique ?

**Comment by lenny31** [comment]
Bonjour.
Le géocodage ne devrait-il pas trouver l'adresse toute proche https://www.openstreetmap.org/node/790857493 ?
Pour contact:*  le wiki en parle à cet endroit $ “Règles de priorités entre sources” de la page https://wiki.openstreetmap.org/wiki/FR:WikiProject_France
et deux conversations :   
https://talk-fr.openstreetmap.narkive.com/43MX7sbk/osm-talk-fr-adresses-sur-batiment-et-sur-point-a-l-interieur
http://forum.openstreetmap.fr/viewtopic.php?f=2&t=7005

cordialement

**Comment by amatissart** [comment]
Il y a bien un problème avec le géocodage inversé lorsque plusieurs adresses très proches sont présentes. Merci pour le signalement !

Un fix a été proposé et devrait être intégré prochainement (cf https://github.com/CanalTP/mimirsbrunn/pull/288)

**Comment by lmagreault** [comment]
> Je ne connais pas cette pratique d'utilise `contact:*` pour ne pas dupliquer d'adresses et ces tags ne sont pas documentés. Est-ce vraiment une bonne pratique ?

Bonjour,

C'est une solution élégante qui fait l'objet d'une proposition :
[](https://wiki.openstreetmap.org/wiki/Proposed_features/House_numbers/Bremen_Schema)

On en trouve quand même 5000 en France sur taginfo :
[](https://taginfo.openstreetmap.fr/keys/contact%3Astreet#map)
