### ISSUE TITLE
Phone number formatting

### ISSUE THREAD

**Issue by JulesLassara** [QwantResearch/qwantmaps#29]
Hello,

I just noticed a little formatting problem about some phone numbers. We can find these two format : +33123456789, and +33 1 23 45 67 89.
An example :
→ https://bit.ly/2sYY5AS (first format)
→ https://bit.ly/2MIi8wm (second format)

Moreover, I have a suggestion. When we are selecting a business or service, it would be nice to keep its name or icon displayed when we are zooming out on the map to keep in mind where we are going to if we have several destinations (for future itineraries).

Thank you !

**Comment by JulesLassara** [comment]
Another suggestion : may be able to add any address to favorites, and not only places like restaurants, school etc.

**Comment by nlehuby** [comment]
thanks for your feedbacks and suggestions :heart: 

You will be able to add an address to your favorites soon!

About the phone number, you are right, we need to improve the formatting! 
If you or anyone else want to contribute by working on this enhancement, please create an issue in [Idunn repository](https://github.com/qwantresearch/idunn) so we can provide guidance: we already have a few ideas about how to handle it.

PS : @JulesLassara if you have other suggestions or bugs, please create a new issue for each topic, it will be easier for us to provide you explanations or updates about them ;)

**Comment by jbgriesner** [comment]
Your issue @JulesLassara should have been fixed by [this PR](https://github.com/QwantResearch/idunn/pull/61).
