### ISSUE TITLE
Opening hours not rendered in Qwant Maps when months are present in opening_hours

### ISSUE THREAD

**Issue by sfkeller** [QwantResearch/qwantmaps#30]
Opening hours are not rendered in Qwant Maps POI detail when months are present in OSM tag "opening_hours".

This seems unrelated to #15 and https://github.com/rezemika/humanized_opening_hours/issues/26 .

Here are about 100 examples, not checked if valid (first column is the osm_id, r are OSM relations else it's OSM nodes):

> r9135399;Wallbach Bad;May-Oct: Mo-Fr 10:00-20:00; We 08:00-22:00; Sa-Su 10:00-19:00; Nov-Apr: Mo-Th 10:00-20:00; We 08:00-22:00; Fr 10:00-22:00; Sa-Su 10:00-19:00
r8428062;Seebad Enge;09:00-20:00; May 10-May 27,Sep 03-Sep 16: 09:00-19:00; Sep 17-May 09: off
r8425452;Seebad Utoquai;May 10-Sep 23: 07:00-20:00
r7662841;Regio Badi Sense;May 5-Jun 16: 09:00-19:00; Jun 17-Aug 14: 09:00-21:00; Aug 15-Sep 16: 09:00-19:00; Sep 17-May 4: off
r7564129;Hallenbad Murten;Sep-May: Mo 14:00-21:00; Tu-Fr 09:30-21:00; Sa-Su 09:30-18:00
r6748410;Iberg;Apr-Oct: 10:00-19:00
r5911093;Campingplatz Nufenen;Jun-Sep 24/7
r4471279;Seeteufel;2018 Mar 1-2018 Nov 5 Mo-Su 09:30-18:00; 2018 Nov Su 11:30-18:00; 2019 Feb Su 11:30-18:00
r3900377;Badeanlage Weiermatt;May-Sep 09:00-19:00
r3267311;Piscine de Colovray;May-Jun 09:00-20:00; Jul-Aug 09:00-20:30; Sep 10:00-19:00
4687934;Alter Botanischer Garten;Oct 1-Feb 28 08:00-18:00; Mar 1-Sep 30 07:00-19:00
14390375;Freibad Letzigraben;May-Sep 07:00-20:00
23463043;Masoala-Halle;Mar-Oct: Mo-Su,PH 10:00-18:00; Nov-Feb: Mo-Su,PH 10:00-17:00
24645505;Schwimmbad Baden;May,Sep: 10:00-19:00; Jun: 09:00-20:00; Jul,Aug: 09:00-21:00
26844166;Sea Life Centre;10:00-17:00; Aug 10:00-18:00; Dec 24: off
27841237;Strandbad Mythenquai;May 10-Sep 16: 09:00-20:00
28229006;Bois du Petit-Château;08:00-18:00; Nov-Feb 08:00-17:00 “winter”
29995256;Chinagarten Zürich;Mar 17-Oct 21 11:00-19:00
30025128;Märtplatz;Sa 07:00-13:00; Jun-Aug: We 07:00-13:00
32449531;Helbling Bootswerft Schmerikon;Jan-Dec: Mo-Fr 07:30-12:00,13:30-17:00; Apr-Aug: Sa-Su 10:00-12:00,14:00-17:00
33678757;Zoo Rothaus;Nov-Mar closed; Apr-Oct Mo-Su 10:00-18:30
34525787;Rifugio Prabello;Jun-Sep; We-Mo
36951196;Parco San Michele;Mar 1 - Sep 30: 06:00-23:00; Oct 1 - Feb 28: 07:00-21:00
37171222;Schwimmbad Büel;May,Sep Mo 11:00-19:00; May Tu-Su 09:00-19:00; Jun-Aug Mo 11:00-20:00; Jun-Aug Tu-Su 09:00-20:00
41016083;Berggasthaus Alter Säntis;May-Oct
42298957;Edeka;Mar Su[-1]-Oct Su[-1] -1 day: 07:00-20:00; Oct Su[-1]-Mar Su[-1] -1 day: 07:00-19:00; Su,PH off
45782717;Albishaus;Jan-Apr We-Su 10:00-23:00; May-Sep 10:00-23:00; Oct-Dec We-Su 10:00-23:00
46771094;Jardin Botanique de Lausanne;Mar,Apr,Oct: 10:00-17:30; May-Sep: 10:00-18:30
46970411;Flachs- und Weinbaumuseum;Apr-Oct: Su[1] 14:00-17:00
47222485;TCS Camping Genève - Vésenaz;08:30-12:00,14:30-19:00; Jul 02-Aug 20: 08:00-21:00; Oct 10-Mar 23 off
47249871;Tägi Minigolf;May-Sep: 09:00-20:00
49138310;Gurli;May-Oct: Th-Sa 08:30-23:00; May-Oct: Su 08:30-22:00; May-Oct: Mo off; Nov-Apr: off
52056053;Restaurant Einsiedelei;May-Aug: We-Su 11:00+; Mo-Tu off; Sep-Oct,Apr:We-Sa 14:00+; Su 11:00-22:00; Mo-Tu off; Nov-Mar: We-Sa 15:00+; Su 11:00-22:00; Mo-Tu off
56877256;Hohenklingen;Mar-Apr: We-Sa 10:00-24:00, Mar-Apr: Su 10:00-18:00, May-Sep: Tu-Sa 10:00-24:00, May-Sep: Su 10:00-18:00, Oct-Dec: We-Sa 10:00-24:00, Oct-Dec: Su 10:00-18:00
60674548;Tourist Information;Mo 13:30-17:00; Tu-Fr 09:30-12:00, 13:30-17:00; Jul-Aug: Sa 09:30-12:00, 13:30-17:00; PH off
65227828;Schaukäserei;May 10:00-16:00; Jun-Sep 09:00-17:30; Oct 10:00-17:00
66318112;Sternwarte Muesmatt;Jun-Aug Mo-We off; Th 22:00+; Fr-Su off; Dec-Feb Mo-We off; Th 20:00+; Fr-Su off
66753850;Textildruckmuseum Mittelweiherburg;Apr-Oct: We,Sa 17:00-19:00, Su,PH 10:00-12:00; "Führungen auch nach telefonischer Vereinbarung"
71171918;Chamonna Lischana;Jun Th[3] - Oct Su[2] "Opening dates in start and end of season may differ, check for certainty the website."
71444591;Café des Mines;Apr 1-Nov 1: Mo-Su 09:30-17:00; Nov 2-Mar 31 Fr,Sa,Su 11:00-16:00
73029392;Cimitero Chiasso;Mar 01-Nov 15: Mo-Su 07:00-20:00; Nov 16-Feb 28: Mo-Su 07:30-19:00
73029393;Cimitero Morbio Inferiore;Mar 01-Nov 15: Mo-Su 08:00-21:00;Nov 16-Feb 28: Mo-Su 08:00-18:00
75916673;Piscine de Payerne;May-Sep 09:00-20:00
76279159;Schifflände;Mar 15-31 10:00-22:00; Mar 15-31 Tu,We off; Apr 01-May 31 10:00-22:00; Apr 01-May 31 We off; Jun 01-Nov 04 10:00-22:00
86150678;Volg Montfaucon;Mo-Fr 06:00-18:30; Sa 06:00-17:00; Su 08:00-12:00; Aug 01 off
88963179;Schlosskirche;Mo-We,Fr-Su 09:00-18:00; Th 11:00-18:00; Nov-Mar off
89060423;Botanischer Garten der Universität Zürich;Mo-Fr 08:00-18:00; Sa-Su 08:00-17:00; Mar-Sep: Mo-Fr 07:00-19:00; Mar-Sep: Sa-Su 08:00-18:00
89967889;Bürkliplatz;06:30-21:45; Nov-Mar 06:30-20:45
92480707;Maus Haus;Nov-mar 09:00-16:00; apr-oct 09:00-19:00Nov-mar 09:00-16:00; apr-oct 09:00-19:00
94381932;Abenteuerland Walter Zoo;Mar - Oct: 09:00 - 18:30, Nov - Feb: 09:00 - 17:30
95740810;Kleine Schanze;Jan-Apr off; May-Sep: Mo-Su 10:00-23:30; Oct-Dec off
95857294;Strandbad Kilchberg;May,Sep: 09:00-19:00; Jun-Aug: 09:00-20:00
96682327;Minigolf Romanshorn;Apr-Sep: Mo-Su,PH 09:00-22:00
97869465;Bergwerkmuseum;Apr-Nov Sa 13:00-16:30
100059150;2Legends Boardstores;Mar-Oct: Tu-We 14:00-18:30, Th 14:00-19:30, Fr 09:00-13:00, 14:00-18:30, Sa 09:00-16:00
100595576;Gasthof Alte Post;Mar 16-Dec 15 Tu-Su 11:30-22:00
102016464;Fischstube;Apr-Oct: 11:30-24:00; Apr,Oct: Mo off
103945550;Museum Bellerive;Tu-Su 10:00-17:00; Jun-Sep: Th 10:00-20:00
104278766;Gletschergarten Luzern;Apr-Oct 09:00-18:00; Nov-Mar 10:00-17:00
104729892;Campingplatz Lienheim;Apr-Oct
105578393;Thomet und Lüscher Sport AG;Apr-Nov: Tu-Fr 09:00-18:30; Sa 09:00-16:00; Dec-Mar: Mo-Th 08:30-18:30; Fr 08:30-20:00; Sa 08:00-16:00
107186368;Laib & Seele;Nov-Mar: Mo-Fr 06:00-19:00;Nov-Mar: Sa 07:00-18:00;Nov-Mar: Su 08:00-18:00;Apr-Oct: Mo-Fr 06:00-20:00;Apr-Oct: Sa 07:00-20:00;Apr-Oct: Su 08:00-20:00
107469737;Hafen Tiefenbrunnen;Mar-Oct 00:00-24:00
107943940;Schloss Schenke;May-Oct: Sa-Su
110570463;Schwimmbad Oberwinterthur;May-Sep: Mo 10:00-19:00; May-Sep: Tu-Su 09:00-19:00;Jun-Aug: Mo 10:00-20:00; Jun-Aug: Tu-Su 08:00-20:00
111866385;La Crêpecidre;Dec 1-Apr 15 10:00-17:00; Mo-Tu closed
115056435;Aliverti;Mo_off; Tu-Fr_07:30-12:00,13:15-18:15; Sa_Mar-Oct:_Sa_08:00-16:00; Nov-Feb:_Sa_09:00-15:00
116254459;Tierpark Dählhölzli;Mar 01-Oct 15: Mo-Su,PH 08:30-19:00; Oct 16-Feb 28: Mo-Su,PH 09:00-17:00
116522155;Schloss Wiesendangen;Su[1] 14:00-17:00; Aug off
117572628;Museum Langmatt;Tu-Fr 14:00-17:00; Sa,Su 11:00-17:00; Dec 15-Mar 01 off
117769063;Strandbad Tiefenbrunnen;May 19-Sep 14: 09:00-20:00
124235226;Druesberghütte;Jun 1-Oct Su[-1] 08:00-18:00; Dec 1-Mar Su[-1] 08:00-18:00;"Auf Vorbestellung auch Donnerstag bis Samstag bis 23:00"
124903796;;Apr-Oct Mo-Su 10:00-22:00
125066698;Franz;Mo closed; Tu-Th 09:00-23:00; Fr-Sa 09:00-00:30; Su[-1] 10:00-17:00; Nov-Apr: Su 10:00-17:00
125707686;Müller Bräu Biergarten Baden;Mo-Fr Fr 11:30-23:00; Sa 16:00-23:00; Su 16:00-22:00; Oct-Apr off
125826449;Restaurant Bärghuus;Jun: Mo-Su 11:00-14:30; Jul-Sep: Mo-Fr 11:00-14:30; Sa-Su 08:30-14:30; Oct: Mo-Su 11:00-14:30
126325579;Wertstoffanlage;Jan-Mar Sa 09:30-11:30;Apr-Oct Tu 17:30-18:30;Apr-Oct Sa 09:30-11:30
129116469;;Apr,May,Jun,Sep,Oct: Su[2] 14:00-16:00
130910712;;Apr-Sep sunrise-21:00; Oct-Mar sunrise-19:00
131605934;Stiftsbibliothek;Mo-Sa 10:00-17:00, Su 10:00-16:00; Nov: "Im November3 Wochen geschlossen" || "Spezielle Öffnungszeiten siehe auf der Homepage"
131974568;Josef Hage;Mo-Fr 09:00-12:15,13:30-18:00; Sa 09:30-13:00; Su,PH off; Nov-Feb: Mo off
136033053;Zoo Zürich;Mar-Oct: Mo-Su,PH 9:00-18:00; Nov-Feb: Mo-Su,PH 9:00-17:00
140659319;Buvette Les Seythours;May-Sep 10:00-23:00
144194873;Seerettungsdienst Küsnacht;Apr-Oct: Sa 13:30-19:00; Su 11:00-19:00
148325054;Zürcher Schülerheim Victoria;Mar 01-Oct 31
149059088;Dorfmuseum;Mar-Nov Su[1] 14:00-17:00; Aug off
161576504;Vitamare;May 1-Sep 11: Mo-Fr 09:00-21:00, Mo-Fr sunset-sunrise off, Sa,Su,PH 09:00-19:00; Sep 12-Apr 30: Mo,Tu,Th,Fr 13:30-21:30, We 12:00-21:30, Sa,Su,PH 10:00-17:00
163850331;Campingplatz Gerbe;Mar-Oct
164437818;Schwanbar;Jun-Sep: mo-th 17:00-24:00; Fr 17:00-02:00; Sa 11:00-02:00; Su 13:00-24:00
167015001;Gemeindeverwaltung Niederweningen;Mo 08:15-11:30,14:00-18:00; Tu-Th 08:15-11:30,14:00-16:30; Fr 07:00-11:30; Jul Mo[3]-Aug Sa[2]: Mo-Fr 08:15-11:30 open "verkürzte Sommeröffnungszeiten", Jul Mo[3]-Aug Sa[2]: Mo 14:00-18:00 open "verkürzte Sommeröffnungszeiten"
168512083;Gartenbad Obersiggenthal;May 01-Sep 16: Mo-Fr 09:00-20:30; May 01-Sep 16: Sa,Su 09:00-19:30
172301756;Teehüsli Fallätsche;PH,Su 10:00-16:00;Dec 24-25,Dec 31 off
173382311;Landgasthof zur Traube;Mo-Fr 08:30-24:00; Tu,We 08:30-14:00; Sa 11:30-23:00; Su 10:00-17:30; Apr-Oct: Su 10:00-22:00
174376997;Schwimmbad Sandhöli;Mo 11:00-19:00; Tu-Su 09:00-19:00; Jun-Aug: Mo 11:00-20:30; Jun-Aug: Tu-Su 09:00-20:30; Sep 20-May 8: off
176306617;Minigolf;Mo-Su 10:00-22:00; Oct 16-Mar 14 off
176979890;Oberer Turm;Apr 15-Oct 15: Sa,Su 14:00-17:00
179426743;Roggenloch;Jun 1-Oct 15 08:00-24:00;"Anfang und End der Saison ist jedes Jahr anders."
184447002;Thun Panorama;Mar-Nov: Tu-Su 11:00-17:00

**Comment by nlehuby** [comment]
Hi Stefan,

Thanks for your contribution.
I'm not sure to understand your issue: what do you mean by "Opening hours are not rendered in Qwant Maps POI detail" ?

If you look at these ones for instance, there is an opening_hours block displayed, and its value seems good to me:

r8425452;Seebad Utoquai;May 10-Sep 23: 07:00-20:00
https://www.qwant.com/maps/place/osm:relation:8425452@Seebad_Utoquai#map=18.00/47.3617595/8.5463457
![in Qwant Maps](https://user-images.githubusercontent.com/919962/53021352-538d1780-3459-11e9-8e90-23be25184f55.png)


r7662841;Regio Badi Sense;May 5-Jun 16: 09:00-19:00; Jun 17-Aug 14: 09:00-21:00; Aug 15-Sep 16: 09:00-19:00; Sep 17-May 4: off
https://www.qwant.com/maps/place/osm:relation:7662841@Regio_Badi_Sense#map=18.00/46.9032344/7.2306477

r7564129;Hallenbad Murten;Sep-May: Mo 14:00-21:00; Tu-Fr 09:30-21:00; Sa-Su 09:30-18:00
https://www.qwant.com/maps/place/osm:relation:7564129@Hallenbad_Murten#map=18.00/46.9264994/7.1103392

184447002;Thun Panorama;Mar-Nov: Tu-Su 11:00-17:00
https://www.qwant.com/maps/place/osm:way:184447002@Thun_Panorama#map=18.00/46.7456790/7.6353182

**Comment by sfkeller** [comment]
Sorry: I checked following occurences on Qwant Maps, where opening_hours are not displayed there  (although there are entries in OSM) - and thought the common reason is months (which obviously is not the reason):

> https://www.qwant.com/maps/place/osm:way:203451072@Rathaus/#map=18/47.2263220/8.8163994
> https://www.qwant.com/maps/place/osm:node:1355269726@Olivia/#map=18/47.2266159/8.8166686
> https://www.qwant.com/maps/place/osm:node:6019702272@Frauenhof/#map=18/47.2269427/8.8164762
> https://www.qwant.com/maps/place/osm:way:194039270@Dieci/#map=18/47.2257003/8.8152562
> https://www.qwant.com/maps/place/osm:node:5838519294@Kingz/#map=18/47.2261551/8.8191465
> 

Now, I'm unsure where the problem is.

**Comment by amatissart** [comment]
Hi @sfkeller 

In the first case, there is no "opening_hours" tag on the OSM object (https://www.openstreetmap.org/way/203451072, building with tourism=attraction).
But opening_hours are correctly displayed on the nearby restaurant, represented as a separate node: https://www.qwant.com/maps/place/osm:node:1355269772
The confusion may be due to how both POIs are represented very close to each other, and need to be zoomed in to be distinguished on Qwant Maps.

Other cases are caused by invalid values that exist in OSM data
 * https://www.openstreetmap.org/node/1355269726 (note the long dashes in tag value)
 * https://www.openstreetmap.org/node/5838519294 (incomplete time range on Monday),

or have been corrected recently and are not up-to-date in our database yet. We plan to apply daily OSM updates very soon (https://github.com/QwantResearch/qwantmaps/issues/27)

[The python library](https://github.com/rezemika/humanized_opening_hours) we are using to parse `opening_hours` values is still under development ; we'd like to contribute to it. And [the OSM grammar for opening_hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification) is quite complex. 

So we will definitely need feedback about this. Thanks for your alertness!

**Comment by sfkeller** [comment]
Thanks. 
You're correct about the errors in OSM data or about missing tags there.

BTW. A lab staff of mine is experimenting with a small tool to help people enter valid opening_hours: https://codepen.io/BSee/full/WLbLGW .
