### ISSUE TITLE
Add POI fitness_centre

### ISSUE THREAD

**Issue by Floflr** [QwantResearch/qwantmaps#35]
Ajouter dans Qwant Maps les POI **fitness_centre**

![Rendu Qwant](https://user-images.githubusercontent.com/18467487/55239714-8d5ef400-5237-11e9-957e-b7b3223e3843.png)
![Rendu OSM](https://user-images.githubusercontent.com/18467487/55239716-8e902100-5237-11e9-9a76-59b53924f2a4.png)

**Comment by jbgriesner** [comment]
Thanks for this interesting suggestion: we will import these POI as soon as possible and let you know the evolution.

**Comment by amatissart** [comment]
tracked in #83
