### ISSUE TITLE
Add POI amenity=charging_station

### ISSUE THREAD

**Issue by Postit2019** [QwantResearch/qwantmaps#37]
Is it possible to add charging stations for electric cars?

https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station

capacity=
socket:<type>=number
opening_hours=*
...

This would be a nice feature for all people with an electric vehicle.

**Comment by jbgriesner** [comment]
We'll study the possibility to add this feature, thanks for the suggestion :)

**Comment by amatissart** [comment]
tracked in #83
