### ISSUE TITLE
Germany: House number is displayed before street name.

### ISSUE THREAD

**Issue by Postit2019** [QwantResearch/qwantmaps#38]
It would be more logical in Germany to display the house number after the street name and not vice versa.

Correct: Street 1 
Qwant: 1 Street

**Comment by jbgriesner** [comment]
Thanks to help us to improve Qwant Maps.
This is indeed an important problem: outside of France we haven't yet any easy way to format addresses in the local format for each country in the world. We are working on this issue though.

**Comment by amatissart** [comment]
Good news, our geocoder [Mimirsbrunn](https://github.com/CanalTP/mimirsbrunn/) is now using an international address formatter: https://github.com/CanalTP/address-formatter-rs

We are currently working on integrating its latest features into Qwant Maps. 
See https://github.com/QwantResearch/fafnir/pull/30 for more details

**Comment by amatissart** [comment]
This is now fixed in production:  
https://www.qwant.com/maps/place/osm:way:18578139@Neues_Museum
