### ISSUE TITLE
distant streets assigned to pois

### ISSUE THREAD

**Issue by richlv** [QwantResearch/qwantmaps#46]
POIs that do not have an explicit address assigned have a bit weird, distant street auto-assigned - seems to be offset to the SE.

This might be partially solved by #16, but there would still be cases of POIs without building outlines mapped and other scenarios that would benefit from a more correct auto-assignment.

Examples:

* https://www.qwant.com/maps/place/osm:node:5922821337@Pas%C4%93dn%C4%ABca is listed as "Dīriķu iela", but that street is way to the east.
* https://www.qwant.com/maps/place/osm:node:321681651@Pab%C4%93rzs is listed as "Kuršu iela", but that street is way to the south.

**Comment by richlv** [comment]
Although here's an example of the auto-assigned street being to the NE, so the direction is not uniform: https://www.qwant.com/maps/place/osm:way:92202427@Jaunie_ebreju_kapi .

**Comment by amatissart** [comment]
The coverage for addresses in Qwant Maps has been extended recently to most European countries, including Latvia. So this issue should be mostly solved now that precise addresses can be assigned to POIs.

I am closing this issue for now, don't hesitate to report any problem.
