### ISSUE TITLE
cannot copy detail from poi popup

### ISSUE THREAD

**Issue by richlv** [QwantResearch/qwantmaps#47]
Open details of any POI, for example, https://www.qwant.com/maps/place/osm:node:3733396425@KGB_Building_Corner_House .
Try to select and copy detail from the POI popup, like name, translated name, opening hours and so on - while selecting works, selection is lost while the keyboard shortcut for copying is used.

Reproduced on MacOS with Firefox 66.0.3.

**Comment by jbgriesner** [comment]
Thanks for this feedback.
We'll try to reproduce this bug to correct it.

**Comment by amatissart** [comment]
It seems to be fixed, I am closing this issue for now.
