### ISSUE TITLE
hide

### ISSUE THREAD

**Issue by bored-bananaz** [QwantResearch/qwantmaps#48]
Autant profiter que vous soyez français pour vous aider un peut, 

pourquoi pas cacher / réduire la barre de recherche qui est peut etre un peut grosse et cache une partie de la carte, oui on pourrait dézoomer mais bon certains sur internet sont fénéants ...

Bon courage à vous ^^ continuez ca fait plaisir de voir un produit Français qui fonctionne

**Comment by jbgriesner** [comment]
Merci pour ce feedback pertinent.
Le design tel qu'il existe actuellement évoluera très bientôt : nos équipes design tiendront compte de votre retour d'expérience.

**Comment by amatissart** [comment]
Fixed in https://github.com/QwantResearch/erdapfel/releases/tag/v0.2.1 and released in Qwant Maps Beta
