### ISSUE TITLE
Qwant Maps is not working under Brave browser

### ISSUE THREAD

**Issue by TheoGoudout** [QwantResearch/qwantmaps#49]
Since there is some king of partnership between Brave and Qwant, I figured it should be reported. Although, I'm not sure whether it should be reported to Brave team or Qwant team.

**The bug**: Only the searchbar is displayed by default in Brave browser (using either Linux or Windows).
![Screenshot](https://user-images.githubusercontent.com/4125899/57851918-14652d00-77e2-11e9-8ccf-82fe1958b469.png)

**Workaround**: Set Brave device recognition setting to '3rd-party device recognition blocked'.

**Comment by jbgriesner** [comment]
Thanks for your feedback !
We cannot reproduce your problem.
Can you provide us more details about your system ?

**Comment by TheoGoudout** [comment]
**OS**: Ubuntu 18.04.2 LTS - Linux 4.15.0 x86_64
**Browser**: Brave 'Version 0.65.118 Chromium: 75.0.3770.80'

My Brave settings are pretty vanilla (as far as I can remember):
- Ad control -> Block Ads
- Cookie control -> Block 3rd party cookies
- Fingerprinting protection -> Block all fingerprinting
- HTTPS Everywhere -> ON
- Script blocking -> OFF

I can see one "Device recognition attempt" (by qwant.com) being blocked.

Feel free to ask for specific information, and I'll try to provide you with what I can

**Comment by TheoGoudout** [comment]
I just checked the development tools and there is a stack trace in the console tab

![Screenshot from 2019-06-11 16-46-42](https://user-images.githubusercontent.com/4125899/59282034-8ce7ce00-8c68-11e9-9267-17be6848c7ab.png)

Hope this will help!

**Comment by jeroen7s** [comment]
@TheoGoudout Block all fingerprinting is not the default under Brave, the default is block third party fingerprinting.
Blocking all fingerprinting breaks many more websites, like most websites that generate client side images (Like qr codes, see whatsapp web) and many applications relying on WebGL.

**Comment by TheoGoudout** [comment]
My bad. I'm closing this. Sorry for the inconvenience.
