### ISSUE TITLE
Allow for favorites to be created at any location, not just a point of interest.

### ISSUE THREAD

**Issue by BjornRasmussen** [QwantResearch/qwantmaps#50]
Users should be allowed to select any location, not just a point of interest, and then get directions or save that place as a favorite.

**Comment by jbgriesner** [comment]
Thanks for your interesting suggestion !
We will consider to make this feature possible soon !

**Comment by amatissart** [comment]
This is now possible. Click anywhere on the map and you'll be able to add the position to your favorites or share a link with the exact latitude/longitude:
https://www.qwant.com/maps/place/latlon:48.87682:2.37971
