### ISSUE TITLE
Show city and postcode in search results

### ISSUE THREAD

**Issue by jonsger** [QwantResearch/qwantmaps#51]
The search does only include the city at the results, when the POI has  an `addr:city` tag. This is kind of bad, because most of POIs doesn't have the `addr:city` tag. So searching for `media markt nürnberg` results in this:

![media_markt_nürnberg](https://user-images.githubusercontent.com/3876790/58805817-1ff38900-8615-11e9-96c3-ddfe01f31da5.png)

So only two results are actually in Nürnberg and no "Media Markt". There are three in the OpenStreetMap database: [786620520](https://www.openstreetmap.org/node/786620520), [145043755](https://www.openstreetmap.org/way/145043755) and [3709835488](https://www.openstreetmap.org/node/3709835488). Those all have in common, that they don't have `addr:city=Nürnberg`.

Nominatim does better here by getting the city and the postcode from the relations where the POI is in: `https://www.openstreetmap.org/search?query=media markt nürnberg`

![media_markt_nominatim](https://user-images.githubusercontent.com/3876790/58806475-89c06280-8616-11e9-8362-e6828cdc3c87.png)

So to resolve this issue the Qwant Maps search should return the following when searching for `Media Markt Nürnberg`
```
Media Markt
Äußere Bayreuther Straße 80, 90491 Nürnberg
Media Markt
Ipsheimer Straße, 90431 Nürnberg
Media Markt
Reichenthaler Straße, 90473 Nürnberg
```

The postcode is not so important as a first step. The city is key here for the search :)

For me this is an issue which "blocks" me from using Qwant Maps as well as recommending it to other people. Because apart from this I find it one of the best OSM based maps on the internet. Vector based and clicking on POIs for getting information :)

**Comment by jbgriesner** [comment]
Thanks for your relevant feedback !
We are actually working on a solution to handle this kind of admins zones in Cosmogony:
* https://github.com/osm-without-borders/cosmogony/pull/67
* https://github.com/osm-without-borders/cosmogony/pull/84
This should solve your problem as soon as it will be released !
