### ISSUE TITLE
Add marker for specific location

### ISSUE THREAD

**Issue by seb-jean** [QwantResearch/qwantmaps#53]
Hi,

It would be nice to add a marker for specific location because we don't know exactly where location is. For instance for : https://www.qwant.com/maps/#map=12.08/48.8642287/2.3391427

Thanks :)

**Comment by jbgriesner** [comment]
Thanks for your relevant suggestion !
This feature will be possible soon ;)

**Comment by seb-jean** [comment]
Great!

**Comment by amatissart** [comment]
Duplicate of #50, now solved.
