### ISSUE TITLE
Swimming pool ?

### ISSUE THREAD

**Issue by bristow** [QwantResearch/qwantmaps#56]
Hi !

I don't find swimming-pools on Qwant Maps, like here :
https://www.openstreetmap.org/relation/28722#map=18/43.59915/3.85286

and 

https://www.qwant.com/maps/#map=17.43/43.59915/3.85286

Thanks :)

**Comment by MatthieuOSM** [comment]
Hi,

The same happened to me, so I can reproduce it easilly.
