### ISSUE TITLE
ETA is not accurate sometimes.

### ISSUE THREAD

**Issue by Booteille** [QwantResearch/qwantmaps#59]
I have a situation where the real ETA to get to the destination by walking is less than 1min.

Qwant Maps shows 19m for this travel.

Screenshot:
![Screenshot_2019-06-21 Qwant Maps](https://user-images.githubusercontent.com/2203721/59914190-2a39c380-941a-11e9-8b55-876c13fa587e.png)

**Comment by amatissart** [comment]
Thanks @Booteille for your feedback.  
What you're actually seeing is the distance of the route (19 meters). The relevant code has been fixed to show a correct duration too (even if it's less than a minute), and it should be released soon.

**Comment by Booteille** [comment]
Oh. Okay! If it's the distance it takes a lot more sense! Thanks for the fix!
