### ISSUE TITLE
non local search name

### ISSUE THREAD

**Issue by Whenrow** [QwantResearch/qwantmaps#62]
If I search a place (like a city) that is written differently in my language and the local language, the qwant map doensn't translate my term to show the most relevant result.

Example: searching 'Londres' should show me 'London' but instead show me a little village in Argentina (see https://www.qwant.com/maps/place/admin:osm:relation:2268862@Londres#map=14.27/-27.7156001/-67.1397933)
I got the same issue with Lisbonnes/Lisboa 

Edit: I'm logged in with my belgian-fr account

**Comment by jbgriesner** [comment]
Thanks for your feedback.
Qwant Maps search tool is not synchronized with your Qwant account: the Qwant Maps search language depends only on the search language of your browser.
I think you are using a browser with an english search language.
I you change it to "french" then the query "londres" will find the expected London city.

Moreover: we are working on a smarter solution to avoid these manual configurations.

**Comment by Whenrow** [comment]
It was indeed my browser config. 

Thanks :)
