### ISSUE TITLE
Add right-click to place a location on maps

### ISSUE THREAD

**Issue by Sigmun** [QwantResearch/qwantmaps#72]
Is it plan to add markers using right-click directly on the map ?

Sometimes, the address is not found or is to ambiguous that it is convenient to directly place the marker on the map. 

This function can lead to other functionality such as : 
- Information about location
- Navigate to this location
- Place a favorite
- Ask for POI in the neighborhood

**Comment by jbgriesner** [comment]
Yes, it's definitely planned ;)
