### ISSUE TITLE
Wrong street

### ISSUE THREAD

**Issue by umurri** [QwantResearch/qwantmaps#75]
Hi.

The following shop address is wrong (as you can verify on the map):
Hair and Beauty
Salone di bellezza
Via della Rimenbranza (Castelnuovo di Garfagnana)

must be replaced with
Via Guglielmo Marconi (Castelnuovo di Garfagnana)

Thank you.

**Comment by jbgriesner** [comment]
You are right, nice feedback.
We'll correct this problem soon.

**Comment by umurri** [comment]
You're fast as a squirrell !!!



------ Messaggio originale ------
Da: "Jean-Benoit Griesner" <notifications@github.com>
A: "QwantResearch/qwantmaps" <qwantmaps@noreply.github.com>
Cc: "umurri" <umurri@tiscali.it>; "Author" <author@noreply.github.com>
Inviato: 04/07/2019 14:54:06
Oggetto: Re: [QwantResearch/qwantmaps] Wrong street (#75)

**Comment by bristow** [comment]
In the meantime, i've added the street on OpenStreetMap DataBase : https://www.openstreetmap.org/node/6302241866

**Comment by amatissart** [comment]
POIs with street name in tags are now imported correctly. See https://github.com/QwantResearch/fafnir/pull/45 for more details.

Furthermore, the coverage for addresses in Qwant Maps has been recently extended to most European countries, including Italy. So the association between addresses and Points of Interest should be more reliable.

I am closing this issue, don't hesitate to report any problem.
