### ISSUE TITLE
Missing types of objects

### ISSUE THREAD

**Issue by MatthieuOSM** [QwantResearch/qwantmaps#76]
Hi,

I was able in a city to add a jeweller and a tobacco store which have both their icons represented in Qwant Maps.

But here are some objects that are not properly displayed:
Joiner (Menuisier)
Joiner / Carpenter (Menuisier / Charpentier)

The same goes for Ilôt (Islet) that are not displayed at all.

I have to mention that I named all of these items, but nothing appears in Qwant Maps.

This the same issue as in: https://github.com/QwantResearch/qwantmaps/issues/56

**Comment by amatissart** [comment]
tracked in #83
