### ISSUE TITLE
Interface not displayed on full screen with desktop mode in Android

### ISSUE THREAD

**Issue by plarus** [QwantResearch/qwantmaps#77]
Qwant map interface is not displayed on full screen when activating desktop mode in chrome browser for Android.
![Screenshot_20190704_232930_com android chrome](https://user-images.githubusercontent.com/16477554/60688201-05caf600-9eb4-11e9-8705-a0cc7033f140.jpg)

* My smartphone specifications:
Honor play
Android 9
Chrome 75

**Comment by jbgriesner** [comment]
Thanks for raising this issue.
This is indeed a known bug that we are currently fixing.
It should be solved soon.
