### ISSUE TITLE
Germany: Can't start at position in berlin

### ISSUE THREAD

**Issue by BTuschik** [QwantResearch/qwantmaps#81]
Hi,

i tried to start an navigation from "Rethelstr. 6, 12435 Berlin", but the system can not find it.
With input of "rethelstr. 6" there are only french adresses ...
With input of "rethelstr. 6, berlin" i got french and netherland adresses ...
With input of "rethelstr. 6, 12435 Berlin, Germany" only french adresses ...

Other Case ... i tried so search for "Germany" ... first entrie is "New Germnay" in USA ;)
next is "Germany, Berlin" ... first entrie is correct ... wow
next is "Germany, Berlin, Rethelstr." ... i got the germany embassy in new zealand :)

I think its actual not usable for germans.
I hope this was helpful.

Greetings, Ben

**Comment by jbgriesner** [comment]
Thanks for this issue.
Actually we have indeed not enough addresses yet outside of France...

Regarding you other case, what is the search language of your browser ?

**Comment by BTuschik** [comment]
Its german.

**Comment by BTuschik** [comment]
And i also use the uBlock-Plugin - 4yi

**Comment by amatissart** [comment]
The coverage for addresses in Qwant Maps has been extended recently to most European countries. So you should now be able to find addresses in Berlin.

I am closing this issue for now, don't hesitate to report any problem.
