### ISSUE TITLE
Link to OSM

### ISSUE THREAD

**Issue by answerquest** [QwantResearch/qwantmaps#84]
When I click a POI, some details come up. But I know that back in OSM there are many more details. So, please provide a way for user to jump to the equivalent OSM link. Or, provide a link for opening the same map location on OSM for editing etc.

**Comment by jbgriesner** [comment]
This is already possible.
When you click a POI on Qwant Maps the url looks for instance like:
`https://www.qwant.com/maps/place/osm:node:1009073534`
The last part of the url refers to the OSM id.
You have to concatenate this id with the OSM url to get the OSM link:
`https://www.openstreetmap.org/` + `node/1009073534`

However we will consider to add a link that directly proposes the correct "concatenated" link.

**Comment by answerquest** [comment]
> However we will consider to add a link that directly proposes the correct "concatenated" link.

Yep, that's the request. Thanks!

**Comment by bristow** [comment]
:+1: for the request, thanks !

**Comment by amatissart** [comment]
Implemented in https://github.com/QwantResearch/erdapfel/pull/321 
and now deployed to production: https://www.qwant.com/maps/place/osm:way:309089736
