### ISSUE TITLE
Impossible to search for a city of town

### ISSUE THREAD

**Issue by arthuragone** [QwantResearch/qwantmaps#97]
When I try to find a city, I never get the right answer but always a point of interest instead. 

I've tried cities and town of many sizes and even when adding context (like the country of the region). 

I've tried: "Bordeaux" / "Bordeaux, France" / 'Manchester" / "Manchester, England"  / "Rye" / "Rye, Sussex" / "Rye, England" None of this search worked out

![Qwant_Map_Bordeaux](https://user-images.githubusercontent.com/10601027/65427768-5c8cff80-de13-11e9-9752-2b69811d454a.PNG)

**Comment by amatissart** [comment]
This was due to a temporary issue on our production cluster : partial results were returned, excluding cities and administrative zones. It is solved now.

I am closing this issue, don't hesitate to report any other problem in a separate issue.

**Comment by arthuragone** [comment]
> This was due to a temporary issue on our production cluster : partial results were returned, excluding cities and administrative zones. It is solved now.
> 
> I am closing this issue, don't hesitate to report any other problem in a separate issue.

As I'am trying right now, the issue still exist !

**Comment by amatissart** [comment]
> As I'am trying right now, the issue still exist !

Wasn't it due to your browser cache ? Are you still seeing this issue now after refresh ?
